# utf8

name: craft
type: php:7.1
access:
  ssh: admin
build:
  flavor: composer
runtime:
  extensions:
    - imagick
    - mbstring
    - mcrypt
    - redis
relationships:
  db: 'db:mysql'
  cache: 'cache:redis'
  session: 'session:redis'
dependencies:
  nodejs:
    yarn: "*"
web:
  locations:
    '/':
      root: public
      passthru: '/index.php'
      index:
        - "index.php"
      scripts: true
      allow: true
      rules:
        '^(.+)$':
          passthru: '/index.php?p=$1'
variables:
  php:
    disable_functions: phpinfo
    display_errors: Off
    memory_limit: 256M
    'session.save_handler': redis
disk: 2048
mounts:
  '/craft/storage': 'shared:files/craft/storage'
hooks:
  build: |
    yarn install
    yarn run production
  deploy: |
    php -f scripts/platform.sh/deploy.php
    bin/craft clear:cache
    curl -If https://localhost/
