# utf8

name: app
type: php:7.1
build:
  flavor: composer
runtime:
  extensions:
    - imagick
    - mbstring
    - mcrypt
    - redis
relationships:
  db: 'db:mysql'
  cache: 'cache:redis'
  session: 'session:redis'
web:
  locations:
    '/':
      root: public
      passthru: '/index.php'
      index:
        - "index.php"
      scripts: true
      allow: true
      rules:
        '^(.+)$':
          passthru: '/index.php?p=$1'
disk: 2048
mounts:
  '/craft': 'shared:files/craft'
hooks:
  build: mkdir -p craft
  deploy: cp -r src/* craft/
