version: '2'
services:
  http:
    image: nginx:1-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./docker/conf/http/craftcms.conf:/etc/nginx/conf.d/default.tmpl
      - ./docker/conf/http/start.sh:/start.sh
    volumes_from:
      - app
    links:
      - app:app.${COMPOSE_PROJECT_NAME}.dev
    networks:
      - public
      - front
    environment:
      - TZ
      - COMPOSE_PROJECT_NAME
    command: [/start.sh]
  app:
    image: dnunez24/craftcms
    build:
      context: ./docker
      dockerfile: Dockerfile.development
    volumes:
      - ./src:/var/www/html
      - ./docker/conf/app/php.ini:/usr/local/etc/php/conf.d/php.ini
    links:
      - db:db.${COMPOSE_PROJECT_NAME}.dev
      - cache:cache.${COMPOSE_PROJECT_NAME}.dev
      - session:session.${COMPOSE_PROJECT_NAME}.dev
    networks:
      - front
      - back
    environment:
      - CRAFT_ENVIRONMENT=dev
      - TZ
      - COMPOSE_PROJECT_NAME
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - REDIS_PORT
  db:
    image: percona:latest
    ports:
      - '3306:3306'
    volumes:
      - ./docker/conf/db/craftcms.cnf:/etc/mysql/conf.d/craftcms.cnf
    networks:
      - back
    environment:
      - TZ
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
  cache:
    image: redis:3-alpine
    networks:
      - back
    environment:
      - TZ
  session:
    image: redis:3-alpine
    networks:
      - back
    environment:
      - TZ
volumes:
  app:
  db:
networks:
  public:
  front:
  back:
