version: '3.1'

services:
  http:
    depends_on:
      - app
    image: nginx:1.12-alpine
    networks:
      public:
    ports:
      - "80:80"
    volumes:
      - craft:/var/www/craft
      - public:/var/www/html

  app:
    build: .
    depends_on:
      - cache
      - db
      - session
    env_file: .env
    image: craftcms:latest
    networks:
      public:
      private:
    secrets:
      - source: craft_validation_key_v1
        target: craft_validation_key
      - source: mysql_root_password_v1
        target: mysql_root_password
      - source: mysql_password_v1
        target: mysql_password
    volumes:
      - craft:/var/www/craft
      - public:/var/www/html
      # - ./db.php:/var/www/craft/config/db.php
      # - ./general.php:/var/www/craft/config/general.php
      - ./rediscache.php:/var/www/craft/config/rediscache.php
      # - ./php.ini:/usr/local/etc/php/craftcms.ini
    #   - ./craft/plugins:/var/www/craft/plugins
    #   - ./craft/storage:/var/www/craft/storage
    #   - ./craft/templates:/var/www/craft/templates
    #   - ./craft/translations:/var/www/craft/translations
    #   - ./public:/var/www/html

  db:
    env_file: .env
    image: mariadb:10.1
    networks:
      private:
    secrets:
      - source: mysql_root_password_v1
        target: mysql_root_password
      - source: mysql_password_v1
        target: mysql_password
    volumes:
      - db:/var/lib/mysql

  cache:
    command: ["redis-server", "--appendonly", "yes"]
    image: redis:3.2-alpine
    networks:
      private:
    volumes:
      - cache:/data

  session:
    command: ["redis-server", "--appendonly", "yes"]
    image: redis:3.2-alpine
    networks:
      private:
    volumes:
      - session:/data

networks:
  public:
    driver: overlay
  private:
    driver: overlay

secrets:
  craft_validation_key_v1:
    external: true
  mysql_root_password_v1:
    external: true
  mysql_password_v1:
    external: true

volumes:
  cache:
  craft:
  db:
  public:
  session:
