version: '3'
services:
  http:
    image: nginx:1-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - app:/var/www/html
      - ./docker/http/craftcms.conf:/etc/nginx/conf.d/default.tmpl
      - ./docker/http/start.sh:/start.sh
    depends_on:
      - app
    networks:
      - public
      - front
    environment:
      - COMPOSE_PROJECT_NAME
      - TZ
    command: [/start.sh]
  app:
    build:
      context: ./docker/app
    volumes:
      - app:/var/www/html
      - ./config:/var/www/html/config
      - ./public:/var/www/html/public
      - ./storage:/var/www/html/storage
      - ./templates:/var/www/html/templates
      - ./docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - db
      - cache
      - session
    networks:
      - front
      - back
    environment:
      - BASE_URL="http://dev.${COMPOSE_PROJECT_NAME}.com"
      - CRAFT_ENVIRONMENT
      - DB_DRIVER=mysql
      - DB_SERVER="db.${COMPOSE_PROJECT_NAME}_back"
      - DB_NAME=${COMPOSE_PROJECT_NAME}
      - DB_USER=${COMPOSE_PROJECT_NAME}
      - DB_PASSWORD=${COMPOSE_PROJECT_NAME}
      - CACHE_HOST="cache.${COMPOSE_PROJECT_NAME}_back"
      - CACHE_PORT
      - SESSION_LOCATION="tcp://session.${COMPOSE_PROJECT_NAME}_back:${SESSION_PORT}"
      - TZ
  db:
    image: percona:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./docker/db/craftcms.cnf:/etc/mysql/conf.d/craftcms.cnf
    networks:
      - back
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ
  cache:
    image: redis:3-alpine
    networks:
      - back
    environment:
      - TZ
  session:
    image: redis:3-alpine
    networks:
      - back
    environment:
      - TZ
volumes:
  app:
  db:
networks:
  public:
  front:
  back:
