version: '3'
services:
  http:
    image: nginx:1-alpine
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./craft:/var/www/html/craft
      - ./public:/var/www/html/public
      - ./.docker/http/start.sh:/start.sh
      - ./.docker/http/craftcms.conf:/etc/nginx/conf.d/default.tmpl
    networks:
      - public
      - private
    environment:
      - COMPOSE_PROJECT_NAME
    command: [/start.sh]
  app:
    build: .
    volumes:
      - ./bin:/var/www/html/bin
      - ./craft:/var/www/html/craft
      - ./public:/var/www/html/public
      - ./src/plugins:/var/www/html/src/plugins
      - ./composer.json:/var/www/html/composer.json
      # - ./composer.lock:/var/www/html/composer.lock
      - ./.docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - db
      - cache
      - session
    networks:
      - private
    environment:
      - BASE_URL=http://www.${COMPOSE_PROJECT_NAME}.dev
      - CRAFT_BASE_PATH=/var/www/html/craft/
      - CRAFT_APP_PATH=$CRAFT_VENDOR_PATH/craftcms/cms/src/
      - CRAFT_VENDOR_PATH=$CRAFT_BASE_PATH/vendor/
      - CRAFT_FRAMEWORK_PATH=$CRAFT_VENDOR_PATH/yiisoft/yii/framework/
      - CRAFT_CONFIG_PATH=$CRAFT_BASE_PATH/config/
      - CRAFT_PLUGINS_PATH=$CRAFT_BASE_PATH/plugins/
      - CRAFT_STORAGE_PATH=$CRAFT_BASE_PATH/storage/
      - CRAFT_TEMPLATES_PATH=$CRAFT_BASE_PATH/templates/
      - CRAFT_TRANSLATIONS_PATH=$CRAFT_BASE_PATH/translations/
      - CRAFT_ENVIRONMENT=dev
      - DB_DRIVER
      - DB_SERVER=db.${COMPOSE_PROJECT_NAME}_private
      - DB_DATABASE=${COMPOSE_PROJECT_NAME}
      - DB_USER=${COMPOSE_PROJECT_NAME}
      - DB_PASSWORD=${COMPOSE_PROJECT_NAME}
      - DB_PORT
      - CACHE_HOST=cache.${COMPOSE_PROJECT_NAME}_private
      - CACHE_PORT
      - TZ
  db:
    image: percona:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./.docker/db/craftcms.cnf:/etc/mysql/conf.d/craftcms.cnf
    networks:
      - private
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ
  cache:
    image: redis:3-alpine
    networks:
      - private
    environment:
      - TZ
  session:
    image: alpine:3.5
    volumes:
      - session:/var/www/html/craft/storage/runtime/sessions
    command: [/bin/true]
    networks:
      - private
    environment:
      - TZ
volumes:
  db:
  session:
networks:
  public:
  private:
