version: '3'
services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./config:/var/www/html/config
      - ./docker/app/httpd.conf:/etc/httpd.conf
      - ./docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./public:/var/www/html/public
      - ./storage:/var/www/html/storage
      - ./templates:/var/www/html/templates
      - ./vendor:/var/www/html/vendor
    depends_on:
      - db
      - cache
      - session
    networks:
      - public
      - private
    environment:
      - BASE_URL="http://dev.${COMPOSE_PROJECT_NAME}.com"
      - CRAFT_ENVIRONMENT
      - DB_DRIVER=mysql
      - DB_SERVER="db.${COMPOSE_PROJECT_NAME}_back"
      - DB_NAME=${COMPOSE_PROJECT_NAME}
      - DB_USER=${COMPOSE_PROJECT_NAME}
      - DB_PASSWORD=${COMPOSE_PROJECT_NAME}
      - CACHE_HOST="cache.${COMPOSE_PROJECT_NAME}_back"
      - CACHE_PORT
      - SESSION_LOCATION="tcp://session.${COMPOSE_PROJECT_NAME}_back:${SESSION_PORT}"
      - TZ
    command: ["/usr/sbin/httpd", "-f", "-c", "/etc/httpd.conf"]
  db:
    image: percona:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./docker/db/craftcms.cnf:/etc/mysql/conf.d/craftcms.cnf
    networks:
      - private
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ
  cache:
    image: redis:3-alpine
    networks:
      - private
    environment:
      - TZ
  session:
    image: redis:3-alpine
    networks:
      - private
    environment:
      - TZ
volumes:
  db:
networks:
  public:
  private:
