version: '3'
services:
  http:
    image: nginx:1-alpine
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./src:/var/www/html
      - ./docker/http/start.sh:/start.sh
      - ./docker/http/craftcms.conf:/etc/nginx/conf.d/default.tmpl
    networks:
      - public
      - private
    environment:
      - COMPOSE_PROJECT_NAME
    command: [/start.sh]
  app:
    build: .
    volumes:
      - ./src:/var/www/html
      - ./docker/app/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - db
      # - cache
      # - session
    networks:
      - private
    environment:
      - BASE_URL="http://dev.${COMPOSE_PROJECT_NAME}.com"
      - CRAFT_ENVIRONMENT
      - DB_DRIVER
      - DB_SERVER="db.${COMPOSE_PROJECT_NAME}_private"
      - DB_DATABASE=${COMPOSE_PROJECT_NAME}
      - DB_USER=${COMPOSE_PROJECT_NAME}
      - DB_PASSWORD=${COMPOSE_PROJECT_NAME}
      - DB_PORT
      - CACHE_HOST="cache.${COMPOSE_PROJECT_NAME}_private"
      - CACHE_PORT
      - SESSION_LOCATION="tcp://session.${COMPOSE_PROJECT_NAME}_private:${SESSION_PORT}"
      - TZ
  db:
    image: percona:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./docker/db/craftcms.cnf:/etc/mysql/conf.d/craftcms.cnf
    networks:
      - private
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ
  # cache:
  #   image: redis:3-alpine
  #   networks:
  #     - private
  #   environment:
  #     - TZ
  # session:
  #   image: redis:3-alpine
  #   networks:
  #     - private
  #   environment:
  #     - TZ
volumes:
  db:
networks:
  public:
  private:
